name: Dispatch an Update
on:
  push:
    branches:
      - master
jobs:
  dispatch:
    runs-on: ubuntu-24.04
    steps:
      - name: Dispatch updates
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: carlesloriente/topjekyllthemes
          event-type: updating
